### ISSUE TITLE
How to obtain the sequence of a mature protein

### ISSUE THREAD

**Issue by liuzj039** [HommaF/AlphaFold2_chapter#2]
Great job! I've been attempting to replicate your work recently. As mentioned [earlier](https://github.com/HommaF/AlphaFold2_chapter/issues/1), the utilization of mature sequences has a significant impact on the model's accuracy. However, I'm a bit uncertain about how you are acquiring these mature protein sequences. I comprehend that signal peptide sequences can be obtained using signalP and other techniques, but I'm not entirely clear on how you are obtaining the underlined portion of the sequence. Please forgive me if I overlooked something.

![image](https://github.com/HommaF/AlphaFold2_chapter/assets/55271666/3839560d-ad4a-4132-b8c6-23b7449e8547)

**Comment by liuzj039** [comment]
Hi @HommaF, I just found that you mentioned in the article that the closest experimentally resolved protein to the P69B sequence is 1YU6, which is conveniently available on [uniprot ](https://www.uniprot.org/uniprotkb/P00780/entry) and does annotate a segment as prodomain. I was curious to know if you manually reviewed the literature for all the proteins to find their mature sequences, or if there is a high throughput method that you utilized. I apologize for any inconvenience caused and Looking forward to your reply.

**Comment by liuzj039** [comment]
Hi @FelixHomma. I'm very sorry, I seem to @ your previous account.  I apologize for any inconvenience caused.

**Comment by FelixHomma** [comment]
Hi @liuzj039 ,
I'm currently at a conference and will respond properly later today.

**Comment by liuzj039** [comment]
Thank you very much for your quick reply. I apologize again for the many interruptions in a short time. You can reply to me when you have a free moment after the conference, thank you very, very much.

**Comment by FelixHomma** [comment]
Absolutely no problem, apologies for the confusion with my old account, I will need to consolidate those soon.
I am very happy to hear that you are replicating some of our work and your questions are on point.

>  However, I'm a bit uncertain about how you are acquiring these mature protein sequences. I comprehend that signal peptide sequences can be obtained using signalP and other techniques, but I'm not entirely clear on how you are obtaining the underlined portion of the sequence. Please forgive me if I overlooked something.

I unfortunately do not think that you overlooked something. In your example about Epi1, we used its domain annotation found in literature ([Tian et al., 2004](https://www.jbc.org/article/S0021-9258(20)85621-X/fulltext)). Otherwise, I use InterProScan for domain annotation and then remove prodomains ([InterProScan manual](https://interproscan-docs.readthedocs.io/en/latest/); I recommend using [this](https://hub.docker.com/r/interpro/interproscan) containerised version of InterProScan). 
Processing input sequences is still low-medium throughput and a time-consuming step in the protein-protein interaction predictions. This is a step where biological domain knowledge becomes important.
If you come across a method to increase throughput, please let me know!

**Comment by liuzj039** [comment]
Thank you immensely for your quick response. The provided content is exactly what I was looking for. I am grateful for your generosity in sharing.  If I found any techniques to enhance the throughput, I will make sure to share them with you promptly.
